### ISSUE TITLE
Android - Add commits() for delete and clear

### ISSUE THREAD

**Issue by bkayfitz-cara** [jeroentrappers/flutter_keychain#1]
On some android devices, like the Samsung Galaxy S9, if you don't explicitly call commit, shared prefs will not be updated and it will be like you never deleted the key.

``` 
"remove" -> {
    preferences.edit()
    .remove(call.key())
    .commit()
    result.success(null)
}
"clear" -> {
    preferences.edit()
    .clear()
    .commit()
    result.success(null)
}
```

You may also want add `@SuppressLint("ApplySharedPref")` to the method since android studio complains about using commit() over apply().  But in this case, I would think that commit (which synchronously) is the correct behaviour.

**Comment by jeroentrappers** [comment]
Thank you very much for the suggestion. I've applied it and bumped the version. My apologies for the delay. I missed some notifications.
