### ISSUE TITLE
Read from keychain in iOS project

### ISSUE THREAD

**Issue by hx28939** [jeroentrappers/flutter_keychain#13]
Hello! I made a package with flutter and imported it into swift project.
In my swift project, I can read data stored by flutter_keychain in flutter part. However, in flutter package, I can't read data from swift keychain. I tried other keychain package such as flutter_secure_storage. I got the same result.
What's more, in flutter project, I can't use flutter_secure_storage to read data stored by flutter_keychain.
Is there any way I can do to read data stored in swift project? Thanks a lot.

**Comment by jeroentrappers** [comment]
These projects use different identifiers to prefix their keys. This is by design.
Please look into the implementation details.

**Comment by ryanboerner** [comment]
I am running into the same problem. Is there a workaround to be able to share keychain info between an iOS app and a Flutter app on the same device?

**Comment by jeroentrappers** [comment]
> I am running into the same problem. Is there a workaround to be able to share keychain info between an iOS app and a Flutter app on the same device?

for that you need to setup keychain sharing. You can find more info here: https://medium.com/@anshuraguvansi/keychain-sharing-between-applications-on-ios-af1931468e26
