### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by maximilyutin** [jeroentrappers/flutter_keychain#19]
Migrate the package with null safety support

**Comment by wbusey0** [comment]
Hi @jeroentrappers 

Any update on whether you plan to support NNBD for this plugin? I could create a pull-request if you review, merge & publish it.

**Comment by jeroentrappers** [comment]
Yes please create a PR. Thank you!

Op wo 31 mrt. 2021 10:58 schreef wbusey0 ***@***.***>:

**Comment by wbusey0** [comment]
I created PR #20 which migrates to null-safety

**Comment by jeroentrappers** [comment]
> Hi @jeroentrappers,
> 
> I created PR #20 which migrates to null-safety

Thanks for the PR. New version is published.
