### ISSUE TITLE
No implementation found for method.

### ISSUE THREAD

**Issue by dkp123100** [jeroentrappers/flutter_keychain#23]
No implementation found for method put on channel plugin.appmire.be/flutter_keychain

**Comment by jeroentrappers** [comment]
Please create a pull request to fix the issue.

**Comment by dkp123100** [comment]
Hi @jeroentrappers , I am trying to run the below test case and got the 'No implementation found for method put on channel plugin.appmire.be/flutter_keychain' error. 

  group('Test keyValue store status', () {

    test('storeKeyValue -> Failed', () async {
      final result = await FlutterKeychain.put(key: 'test', value: 'test');
      bool dsdas = true;
      expect(dsdas, false);
    });
  });

**Comment by jeroentrappers** [comment]
What platform are you using?

**Comment by dkp123100** [comment]
Android

**Comment by jeroentrappers** [comment]
Please check out the example project to see how to use the code. It is well possible that your tests are not executing within a context where a keychain is available.
