### ISSUE TITLE
Add support for V2 embedding

### ISSUE THREAD

**Issue by Stoisss** [jeroentrappers/flutter_keychain#24]
When I'm running the app this warning pops up:
The plugin `flutter_keychain` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by yukitaka13-1110** [comment]
Any updates?

**Comment by jeroentrappers** [comment]
Merged into v 2.1.0 and published. Thank you everyone who contributed!
