### ISSUE TITLE
Would it be possible to add support for SecAccessControlCreateWithFlags for iOS

### ISSUE THREAD

**Issue by securit** [jeroentrappers/flutter_keychain#26]
With iOS you can restrict access to the keychain based upon the device state (passcode set, unlocked, after first unlock or always) which you have implemented. 

You can also require the user presence -  - Allowing access only when the device is unlocked (the default) may not be secure enough in all cases. If your app provides direct control over a bank account, you can check for the presence of the authorized user at the very last minute before retrieving login credentials from the keychain. This helps secure the account even if the user hands the device in an unlocked state to someone else.

Would it be possible to add this functionality to flutter_keychain?

https://developer.apple.com/documentation/security/keychain_services/keychain_items/restricting_keychain_item_accessibility under Demand User Presence.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=JogvnnaJ8TI
