### ISSUE TITLE
The plugin `flutter_keychain` uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by taluan** [jeroentrappers/flutter_keychain#27]
The plugin `flutter_keychain` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
Please update new version to fix it. Thanks

**Comment by YuriiVasylyshyn** [comment]
@jeroentrappers any update?
