### ISSUE TITLE
Required Gradle version is low

### ISSUE THREAD

**Issue by jargalbat** [jeroentrappers/flutter_keychain#31]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_keychain' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21

**Comment by DanOxlade** [comment]
+1
I was trying to update the Gradle version in my Flutter app due to: https://github.com/flutter/flutter/issues/58247 and came across this issue due to the flutter_keychain package having a very old gradle dependency.

**Comment by meridorkobi** [comment]
I have the same problem. what can we do?

**Comment by jenow** [comment]
> I have the same problem. what can we do?

There's a pull request upgrading the Kotlin version https://github.com/jeroentrappers/flutter_keychain/pull/33

**Comment by meridorkobi** [comment]
I used 
kotlin_version = '1.6.10'

**Comment by jeroentrappers** [comment]
Should be fixed with the recent PR merges
