### ISSUE TITLE
Where the plugin store the data? on the device?

### ISSUE THREAD

**Issue by WONDERJEWEL** [jeroentrappers/flutter_keychain#32]
Where is the storage on the device or ???
iOS?
Android?
Thanks

**Comment by jeroentrappers** [comment]
In the keychain for iOS, and on Android in secure storage

**Comment by akardas16** [comment]
How does this library keep data even after uninstall the app in android? In native android there is no way to keep data on device after uninstall but this library keep same data after uninstall and reinstall the app?
