### ISSUE TITLE
After reinstall the app, the key stored last time was lost[ on Android]

### ISSUE THREAD

**Issue by Flynn2018** [jeroentrappers/flutter_keychain#34]
Would it be available that keep the key stored by this plugin even if reinstall the app?

**Comment by AlexanderHorielko** [comment]
Any progress on that?

**Comment by alechangbiao** [comment]
Yea I'm facing the same issue on Android, on iOS it's working properly though.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=JogvnnaJ8TI

**Comment by guolingege** [comment]
same here
