### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by TheCarpetMerchant** [jeroentrappers/flutter_keychain#36]
Hi,
I'm running into a few of these exceptions using workmanager (spawns a background isolate to do work).
Can you provide an api endpoint to register the plugin under those circumstances ? Thanks !

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=JogvnnaJ8TI

**Comment by jeroentrappers** [comment]
Please create a PR for this usecase
