### ISSUE TITLE
iOS: Xcode 15 runtime error: dyld[2683]: Symbol not found: _OBJC_CLASS_$_NSObject

### ISSUE THREAD

**Issue by idy** [jeroentrappers/flutter_keychain#38]
Steps to reproduce:

1. create an empty fultter iOS project
2. add flutter_keychain as dependency
3. use Xcode to run

It will build successful but report an runtime error: `dyld[2683]: Symbol not found: _OBJC_CLASS_$_NSObject`.

**Comment by idy** [comment]
After some research, I have identified the issue. It seems that there is a problem when attempting to catch an exception of an NSObject within a try-catch block, specifically with the new linker in Xcode 15.

https://github.com/jeroentrappers/flutter_keychain/blob/4635bebaf04a2465205bb6d1b75bd761a5fd9bbe/ios/Classes/FlutterKeychainPlugin.m#L46-L60

It seems to be related to the thread discussed in this post: https://developer.apple.com/forums/thread/735610.

When removing the catch clause for the NSObject, the runtime error mentioned above does not occur.

**Comment by jeroentrappers** [comment]
This seems to be a linker issue. With xcode 14.3.1 I don't seem to be seeing the issue.

**Comment by idy** [comment]
yep, I have already post it on apple developer forum. I hope Apple can fix this issue in the official release of Xcode 15. Otherwise, we will have to submit workaround code for it.

**Comment by AlexandreFQM** [comment]
Problem still occurring in Xcode 15 latest release

**Comment by fsayfitdinov** [comment]
Has anyone found temporary workarounds?

**Comment by idy** [comment]
https://github.com/idy/flutter_keychain

Temporary workaround.

**Comment by XavierChanth** [comment]
@jeroentrappers when can we expect a published fix for this issue?
#40 has been open for a week now.

**Comment by ashu0806** [comment]
With the latest release of Xcode 15 , it's still causing the issue while creating the build , can anyone have a temporary solution for this?

**Comment by axroromonov** [comment]
ty guys , it works

> After some research, I have identified the issue. It seems that there is a problem when attempting to catch an exception of an NSObject within a try-catch block, specifically with the new linker in Xcode 15.
> 
> https://github.com/jeroentrappers/flutter_keychain/blob/4635bebaf04a2465205bb6d1b75bd761a5fd9bbe/ios/Classes/FlutterKeychainPlugin.m#L46-L60
> 
> It seems to be related to the thread discussed in this post: https://developer.apple.com/forums/thread/735610.
> 
> When removing the catch clause(L57-L59) for the NSObject, the runtime error mentioned above does not occur.

ty guys , it works
