### ISSUE TITLE
keys() method not implemented in android or ios

### ISSUE THREAD

**Issue by Vanethos** [jeroentrappers/flutter_keychain#8]
```
// keys - get all keys
  static Future<List<String>> keys() async =>
      await _channel.invokeMethod('keys');
```

Throws  `Unhandled Exception: MissingPluginException(No implementation found for method keys on channel plugin.appmire.be/flutter_keychain)`

Kotlin code: 

```
when (call.method) {
                "get" -> {
                    val encryptedValue: String? = preferences.getString(call.key(), null)
                    val value = encryptor.decrypt(encryptedValue)
                    result.success(value)
                }
                "put" -> {
                    val value = encryptor.encrypt(call.value())
                    preferences.edit().putString(call.key(), value).commit()
                    result.success(null)
                }
                "remove" -> {
                    preferences.edit().remove(call.key()).commit()
                    result.success(null)
                }
                "clear" -> {
                    preferences.edit().clear().commit()
                    result.success(null)
                }
                else -> result.notImplemented()
            }
```

Either this is removed from both the `lib` and documentation, or the implementation should be added for iOS and Android

**Comment by blackbeario** [comment]
I have a situation where I may need to iterate through the iOS keychain for a Device Identity certificate with an unknown name that is distributed by an MDM policy. Therefore I can't easily use the get() method with a key string. 

I seems like the keys() method could be just what I need to find what I'm looking for. So, what would I need to do to recreate this method?
